version: "3"

services:
  nginx-wip:
    restart: always
    image: nginx:1.13.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/site.wip:/usr/share/nginx/html:rw
      - ./nginx/conf.wip.d:/etc/nginx/conf.d:ro
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/letsencrypt:rw
      - ./nginx/certs-data:/data/letsencrypt:rw
