version: "3"

services:
  django:
    restart: always
    build: ./django
    expose:
      - "8000"
    links:
      - postgis
      - redis
    volumes:
      - ./django:/src
      - ./frontend:/frontend
      - ./nginx/site/static:/src/static:rw
      - ./django/media:/usr/share/app/media:rw
      - log_data:/var/log/django
      - media_data:/usr/src/app/media
    command: /usr/local/bin/daphne -b 0.0.0.0 -p 8000 asgi:application

  celery:
    restart: always
    build: ./django
    environment:
      - C_FORCE_ROOT=true
    links:
      - postgis
      - redis
    volumes:
      - ./django:/src
      - log_data:/var/log/django
    command: /usr/local/bin/celery -A peoplebackend worker -B -l info

  nuxt:
    restart: always
    build: ./frontend
    expose:
      - "3000"
    links:
      - django

  nginx:
    restart: always
    image: nginx:1.15.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./django/media:/usr/share/nginx/html/media:rw
      - ./nginx/site:/usr/share/nginx/html:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/letsencrypt:rw
      - ./nginx/certs-data:/data/letsencrypt:rw
    links:
      - django
      - nuxt

  postgis:
    restart: always
    image: mdillon/postgis:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  redis:
    restart: always
    image: redis:4.0.10
    expose:
      - "6379"

volumes:
  postgres_data:
  log_data:
  media_data:
